CREATE OR REPLACE FUNCTION CHECK_CARD_MATCH(
	cardholder_email VARCHAR(100),
    card_number VARCHAR(100),
    card_expiration_date DATE,
    card_cvv INT,
	merchant_country VARCHAR(100)
)
RETURNS BOOL
AS $$
DECLARE
	holder_id INT;
	bool1 BOOLEAN;
	bool2 BOOLEAN;
	merchant_id INT;
BEGIN
	SELECT (CD.CARDHOLDER_ID) INTO holder_id FROM CARDHOLDER_DETAILS CD WHERE CD.EMAIL = $1;
	
	SELECT (C.EXPIRY_DATE > NOW()) INTO bool1
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2;
	
	SELECT (M.MERCHANT_ID) INTO merchant_id FROM MERCHANTS M WHERE M.MERCHANT_NAME ILIKE ('%Internetflix Ltd.%') AND M.COUNTRY_ID = (SELECT C.COUNTRY_ID FROM COUNTRIES C WHERE C.COUNTRY=$5);
	
	IF NOT bool1 THEN
		INSERT INTO TRANSACTIONS (CURRENCY, TRANSACTION_STATUS, TRANSACTION_TIMESTAMP, MERCHANT_ID, TRANSACTION_TYPE_ID, DECLINE_REASON_ID, CARD_NUMBER, CARDHOLDER_ID, ACQUIRER_ID) VALUES
			('FALSE', NOW(), merchant_id, 1, 3, $2, holder_id, 1);
		RETURN FALSE;
	END IF;
	
	SELECT (C.CVV = $4) INTO bool2
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2;
	
	IF NOT bool2 THEN
		INSERT INTO TRANSACTIONS (TRANSACTION_STATUS, TRANSACTION_TIMESTAMP, MERCHANT_ID, TRANSACTION_TYPE_ID, DECLINE_REASON_ID, CARD_NUMBER, CARDHOLDER_ID, ACQUIRER_ID) VALUES
			('FALSE', NOW(), merchant_id, 1, 2, $2, holder_id, 1);
		RETURN FALSE;
	END IF;
	
	IF NOT EXISTS (SELECT C.CARD_NUMBER 
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2) THEN
		RETURN FALSE;
	END IF;

    IF EXISTS(SELECT * FROM CARDS C WHERE CARDHOLDER_ID = holder_id AND C.CARD_NUMBER = $2 AND C.EXPIRY_DATE = $3 AND C.CVV = $4
    ) THEN
        RETURN TRUE;
    ELSE
       RETURN FALSE;
    END IF;
END;
$$ LANGUAGE plpgsql;

--SELECT CHECK_CARD_MATCH('vjorry0@yahoo.co.jp', '1234-5696-3702-9692', '2024-07-02', 789, 'Idonesia');
