CREATE OR REPLACE FUNCTION CHECK_CARD_MATCH(
	cardholder_email TEXT,
    card_number TEXT,
    card_expiration_date DATE,
    card_cvv INT,
	merchant_id INT
)
RETURNS BOOL
AS $$
DECLARE
	holder_id INT;
	bool1 BOOLEAN;
	bool2 BOOLEAN;
BEGIN
	SELECT (CD.CARDHOLDER_ID) INTO holder_id FROM CARDHOLDER_DETAILS CD WHERE CD.EMAIL = $1;
	
	SELECT (C.EXPIRY_DATE > NOW()) INTO bool1
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2;
	
	IF NOT bool1 THEN
		INSERT INTO TRANSACTIONS (TRANSACTION_STATUS, TRANSACTION_TIMESTAMP, MERCHANT_ID, TRANSACTION_TYPE_ID, DECLINE_REASON_ID, CARD_NUMBER, CARDHOLDER_ID, ACQUIRER_ID) VALUES
			('FALSE', NOW(), $5, 1, 3, $2, holder_id, 1);
		RETURN FALSE;
	END IF;
	
	SELECT (C.CVV = $4) INTO bool2
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2;
	
	IF NOT bool2 THEN
		INSERT INTO TRANSACTIONS (TRANSACTION_STATUS, TRANSACTION_TIMESTAMP, MERCHANT_ID, TRANSACTION_TYPE_ID, DECLINE_REASON_ID, CARD_NUMBER, CARDHOLDER_ID, ACQUIRER_ID) VALUES
			('FALSE', NOW(), $5, 1, 2, $2, holder_id, 1);
		RETURN FALSE;
	END IF;
	
	IF NOT EXISTS (SELECT C.CARD_NUMBER 
	FROM CARDS C
	WHERE C.CARDHOLDER_ID = holder_id
	AND C.CARD_NUMBER = $2) THEN
		--add notes saying invalid card number
		RETURN FALSE;
	END IF;

    IF EXISTS(SELECT * FROM CARDS C WHERE CARDHOLDER_ID = holder_id AND C.CARD_NUMBER = $2 AND C.EXPIRY_DATE = $3 AND C.CVV = $4
    ) THEN
        RETURN TRUE;
    ELSE
       RETURN FALSE;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- SELECT CHECK_CARD_MATCH('Veda Jorry', '1234-5696-3702-9692', '2024-07-02', 789, 1);