-- User Signup 
INSERT INTO INTERNETFLIX_CUSTOMER_DATA(CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_EMAIL, PASS_WORD) VALUES ('xxx', 'xxx', 'xxx', 'xxx');

-- User Login
SELECT EXISTS FROM INTERNETFLIX_CUSTOMER_DATA WHERE CUSTOMER_EMAIL = 'xxx' and PASS_WORD = 'xxx';
cmacilraith2x@baidu.com